<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class RelayRequest extends AbstractMigration {
    public function up(): void {
        $this->query("
            create table request (
                id_request int not null primary key generated by default as identity,
                id_user int not null,
                id_filler int,
                id_torrent int,
                id_tgroup int,
                id_category int not null,
                id_release_type int,
                year int,
                encoding text[],
                format text[],
                media text[],
                last_vote timestamptz not null default current_timestamp,
                filled timestamptz,
                created timestamptz not null default current_timestamp,
                modified timestamptz not null default current_timestamp,
                description text not null,
                url varchar(255),
                title varchar(255) not null,
                image varchar(255),
                catalogue_number varchar(60),
                record_label varchar(80),
                log_score int default 0,
                need_log bool not null default false,
                need_cue bool not null default false,
                need_checksum bool not null default false,
                title_ts tsvector generated always as (to_tsvector('simple', title)) stored
            )
        ");
        $this->query("create index rq_user_idx ON request (id_user)");
        $this->query("create index rq_fill_idx ON request (id_filler)");
        $this->query("create index rq_mod_idx ON request (modified)");
        $this->query("create index rq_enc_idx ON request using gin (encoding)");
        $this->query("create index rq_fmt_idx ON request using gin (format)");
        $this->query("create index rq_med_idx ON request using gin (media)");

        $this->query("
            create trigger track_row_count_request
                after insert or delete on request
                    for each row
                        execute function track_row_count('request')
        ");
    }

    public function down(): void {
        $this->table('request')->drop()->save();
    }
}
