<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class RelayRequestMiscTables extends AbstractMigration {
    public function up(): void {
        $this->query("
            create table request_tag (
                id_request int not null,
                id_tag     int not null,
                primary key (id_request, id_tag)
            )
        ");
        $this->query("
            create index reqt_t_idx on request_tag (id_tag)
        ");
        $this->query("
            create table request_vote (
                id_request_vote int not null primary key generated by default as identity,
                id_request int not null,
                id_user int not null,
                bounty bigint not null,
                created timestamptz not null default current_timestamp
            )
        ");
        $this->query("
            create index reqv_r_idx on request_vote (id_request)
        ");
        $this->query("
            create index reqv_u_idx on request_vote (id_user)
        ");
    }

    public function down(): void {
        $this->table('request_tag')->drop()->save();
        $this->table('request_vote')->drop()->save();
    }
}
