<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class AdminPrivileges extends AbstractMigration {
    public function up(): void {
        $this->getQueryBuilder('update') /** @phpstan-ignore-line need more magic */
            ->update('permissions')
            ->set('`Values`',
                serialize([
                    'admin_add_log' => 1,
                    'admin_advanced_user_search' => 1,
                    'admin_audit_edit' => 1,
                    'admin_audit_view' => 1,
                    'admin_bp_history' => 1,
                    'admin_clear_cache' => 1,
                    'admin_create_users' => 1,
                    'admin_dnu' => 1,
                    'admin_donor_log' => 1,
                    'admin_fl_history' => 1,
                    'admin_freeleech' => 1,
                    'admin_global_notification' => 1,
                    'admin_login_watch' => 1,
                    'admin_manage_applicants' => 1,
                    'admin_manage_blog' => 1,
                    'admin_manage_contest' => 1,
                    'admin_manage_fls' => 1,
                    'admin_manage_forums' => 1,
                    'admin_manage_invite_source' => 1,
                    'admin_manage_ipbans' => 1,
                    'admin_manage_navigation' => 1,
                    'admin_manage_news' => 1,
                    'admin_manage_payments' => 1,
                    'admin_manage_permissions' => 1,
                    'admin_manage_polls' => 1,
                    'admin_manage_referrals' => 1,
                    'admin_manage_stylesheets' => 1,
                    'admin_manage_user_fls' => 1,
                    'admin_manage_wiki' => 1,
                    'admin_periodic_task_manage' => 1,
                    'admin_periodic_task_view' => 1,
                    'admin_rate_limit_manage' => 1,
                    'admin_rate_limit_view' => 1,
                    'admin_recovery' => 1,
                    'admin_reports' => 1,
                    'admin_schedule' => 1,
                    'admin_site_debug' => 1,
                    'admin_staffpm_stats' => 1,
                    'admin_tracker' => 1,
                    'admin_view_notifications' => 1,
                    'admin_view_payments' => 1,
                    'admin_view_referrals' => 1,
                    'admin_whitelist' => 1,
                    'artist_edit_vanityhouse' => 1,
                    'can_use_tor' => 1,
                    'edit_unknowns' => 1,
                    'forums_polls_create' => 1,
                    'forums_polls_moderate' => 1,
                    'site_admin_forums' => 1,
                    'site_admin_requests' => 1,
                    'site_advanced_search' => 1,
                    'site_advanced_top10' => 1,
                    'site_album_votes' => 1,
                    'site_analysis' => 1,
                    'site_archive_ajax' => 1,
                    'site_can_invite_always' => 1,
                    'site_collages_create' => 1,
                    'site_collages_delete' => 1,
                    'site_collages_manage' => 1,
                    'site_collages_personal' => 1,
                    'site_collages_recover' => 1,
                    'site_collages_renamepersonal' => 1,
                    'site_collages_subscribe' => 1,
                    'site_database_specifics' => 1,
                    'site_debug' => 1,
                    'site_delete_artist' => 1,
                    'site_delete_tag' => 1,
                    'site_disable_ip_history' => 1,
                    'site_edit_lineage' => 1,
                    'site_edit_requests' => 1,
                    'site_edit_wiki' => 1,
                    'site_forum_autosub' => 1,
                    'site_forum_post_delete' => 1,
                    'site_make_bookmarks' => 1,
                    'site_moderate_forums' => 1,
                    'site_moderate_requests' => 1,
                    'site_search_many' => 1,
                    'site_send_unlimited_invites' => 1,
                    'site_submit_requests' => 1,
                    'site_tag_aliases_read' => 1,
                    'site_top10' => 1,
                    'site_torrents_notify' => 1,
                    'site_unlimit_ajax' => 1,
                    'site_upload' => 1,
                    'site_user_stats' => 1,
                    'site_view_flow' => 1,
                    'site_view_full_log' => 1,
                    'site_view_torrent_snatchlist' => 1,
                    'site_vote' => 1,
                    'torrents_add_artist' => 1,
                    'torrents_delete' => 1,
                    'torrents_delete_fast' => 1,
                    'torrents_edit' => 1,
                    'torrents_edit_vanityhouse' => 1,
                    'torrents_freeleech' => 1,
                    'users_auto_reports' => 1,
                    'users_delete_users' => 1,
                    'users_disable_any' => 1,
                    'users_disable_posts' => 1,
                    'users_disable_users' => 1,
                    'users_edit_avatars' => 1,
                    'users_edit_invites' => 1,
                    'users_edit_own_ratio' => 1,
                    'users_edit_password' => 1,
                    'users_edit_profiles' => 1,
                    'users_edit_ratio' => 1,
                    'users_edit_reset_keys' => 1,
                    'users_edit_titles' => 1,
                    'users_edit_usernames' => 1,
                    'users_give_donor' => 1,
                    'users_invite_notes' => 1,
                    'users_linked_users' => 1,
                    'users_logout' => 1,
                    'users_make_invisible' => 1,
                    'users_mod' => 1,
                    'users_override_paranoia' => 1,
                    'users_promote_below' => 1,
                    'users_promote_to' => 1,
                    'users_reset_own_keys' => 1,
                    'users_view_email' => 1,
                    'users_view_friends' => 1,
                    'users_view_invites' => 1,
                    'users_view_ips' => 1,
                    'users_view_keys' => 1,
                    'users_view_seedleech' => 1,
                    'users_view_uploaded' => 1,
                    'users_warn' => 1,
                    'view_last_seen' => 1,
                    'zip_downloader' => 1,
                ])
            )
            ->where(['Level' => 1000])
            ->execute();
    }

    public function down(): void {
        // no-op
    }
}
